# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "custom_download_strategy"
class RoksCli < Formula
  desc "Software to create fast and easy drum rolls."
  homepage "https://github.com/ibmintegration/roks-cli"
  version "0.3.7"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/ibmintegration/roks-cli/releases/v0.3.7/roks-cli_0.3.7_macos_x86_64.tar.gz", :using => CurlDownloadStrategy.
    sha256 "cc37e96a87be90e5426d911e81741aea82d41725a39592e6ac43ab3f2093edb3"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/ibmintegration/roks-cli/releases/v0.3.7/roks-cli_0.3.7_linux_x86_64.tar.gz", :using => CurlDownloadStrategy.
      sha256 "9c5e81adabd22cddaf5889d297ad035abde3055292ccbff6999dab06755e01ab"
    end
  end
  
  depends_on "git"
  depends_on "zsh"
  
  conflicts_with "svn"
  conflicts_with "bash"

  def install
    bin.install "roks"
  end

  def caveats; <<~EOS
    How to use this binary
  EOS
  end

  plist_options :startup => false

  def plist; <<~EOS
    <?xml version="1.0" encoding="UTF-8"?>
  EOS
  end

  test do
    system "#{bin}/roks --version"
  end
end
