# This file was generated by GoReleaser. DO NOT EDIT.
class RoksCli < Formula
  desc "Command Line Utility to configure and manage OpenShift and IBM Cloud Pak for Integration."
  homepage "https://github.com/ibmintegration/roks-cli"
  version "0.3.8"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/ibmintegration/roks-cli/releases/v0.3.8/roks-cli_0.3.8_macos_x86_64.tar.gz", :using => CurlDownloadStrategy.
    sha256 "88f488106a1967ac4e9605eb2697fcc8713a7c451637162f473e3f8b311ba990"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/ibmintegration/roks-cli/releases/v0.3.8/roks-cli_0.3.8_linux_x86_64.tar.gz", :using => CurlDownloadStrategy.
      sha256 "9261af256a4810b0f3c036ffd91899fb22a23d3e41c1cdc3bc4ba0e71844476b"
    end
  end
  
  depends_on "git"
  depends_on "zsh"
  
  conflicts_with "svn"
  conflicts_with "bash"

  def install
    bin.install "roks-cli"
  end

  def caveats; <<~EOS
    How to use this binary
  EOS
  end
end
